[Server]
	#Backpack damage probability. Multiplied on level difficulty (hard - 3x) 
	#Default: 0.2
	# Default: 0.2
	# Range: 0.0 ~ 1.0
	base_damage_probability = 0.2
	#Tank volume. 
	#Default: 27
	# Default: 27
	# Range: 9 ~ 54
	tank_volume = 27
	#The speed limit 
	#Default: 4.0
	# Default: 4.0
	# Range: 2.2 ~ 9.9
	jet_speed = 4.0
	#The thrust of single jet 
	#Default: 2.2
	# Default: 2.2
	# Range: 1.1 ~ 3.9
	jet_thrust = 2.2
	#Jet cool-down in ticks. 
	#Default: 20
	# Default: 20
	# Range: 5 ~ 100
	jet_cooldown = 20
